language: node_js
node_js:
  - 10
env:
  global:
    - RELEASE_VERSION=1.2
cache:
  directories:
  - node_modules
install:
- npm install
script:
- echo $TRAVIS_PULL_REQUEST_BRANCH
- echo $RELEASE_VERSION
- echo 'test string'
- 'if [ ${TRAVIS_PULL_REQUEST_BRANCH} = "test-branch" ]; then
    echo "IFBLOCK"
  fi'
- set |grep TRAVIS
- npm run test --coverage
- npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET_UAT
  skip_cleanup: true
  upload-dir: 1.2
  on:
    branch: test-branch
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  on:
    branch: master


