language: node_js
node_js:
  - 10
env:
  global:
    - RELEASE_VERSION=1.2
    - DEFAULT_LOCALHOST=https://localhost:3000
    - PROD_URL=https://dfslh8qg8d862.cloudfront.net/prod/${RELEASE_VERSION}
    - UAT_URL=https://dfslh8qg8d862.cloudfront.net/uat/${RELEASE_VERSION}
cache:
  directories:
  - node_modules
install:
- npm install
provider: script
script:
  bash before_uat_scripts.sh
before_deploy:
  bash before_uat_scripts.sh
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET_UAT
    skip_cleanup: true
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    on:
      branch: master


